### ISSUE TITLE
Add custom properties plugin

### ISSUE THREAD

**Issue by reaktivo** [Travix-International/postcss-travix#4]
### Background
We're in the process of migrating scss style definitions into valid css. We cannot to this via a simple `scss -> css` compilation, since we would loose the variable references.

The current implementation of the css variables polyfill we are using in RWD in severely limited, mainly the fact that we cannot define css variables in the same file we are using them. For example, the following css variable values will not be replaced:

```css
:root {
  --background-color: red;
}

#example {
  background-color: var(--background-color);
}
```

### Proposal

CSSNext solves this problem and others by resolving variable references at compile time, when they're available. When a variable definition is not available, it leaves as is, which is good, since this allows us to resolve it via the runtime polyfill.

```css
/* theme.css */
:root {
  --something: red;
}
```

```css
/* myComponent.css */
:root {
  --buttonBackground: var(--something);
}

button {
  background: var(--buttonBackground);
}
```

will convert into:

```css
button {
  background: var(--something); /* this will be resolved by the runtime polyfill */
}
```

**Comment by fahad19** [comment]
Few questions:

* Just the plugin for variables would be enough compared to cssnext? (already discussed)
* How would the variables be known during bundle-time? 
* Do we really want to pass the variables during compile-time?
  * If yes, is it restricted to our monolith? or spreading to Apps too?

**Note**: if we are passing variables during bundle-time for Apps, the need for bundling per Theme arises.

**Comment by reaktivo** [comment]
Implementing `postcss-custom-properties` is enough, so I agree about this point and I'll implement it this way. The reason I initially proposed using the `cssnext` plugin was that it already includes autoprefixing and nesting (via a different, but draft standard, syntax).

The problem I'm trying to solve is not actual inserting of css variable values from other themes, but mantaining reusable variables that are defined on a same file, for example, in scss we sometimes have:

```scss
$checkout-extra__product-container__font-size: 13px;
/ * sometimes we have references to external variables */
$checkout-extra__product-container__font-size: $some-other-variable-defined-elsewhere;
.checkout {
  .product {
    p {
      font-size: $checkout-extra__product-container__font-size;
    }
  }
}
```

I would like to create tooling that will convert the previous into:

```css
:root {
  --checkout-extra__product-container__font-size: 13px;
  /* or possibly a namespaced value like:
  --current-filename-checkout-extra__product-container__font-size: 13px
  */
  --checkout-extra__product-container__font-size: var(--some-other-variable-defined-elsewhere);

}
.checkout {
  .product {
    p {
      font-size: var(--checkout-extra__product-container__font-size);
    }
  }
}
```

The beauty is that only variables that can be resolved at compile time (for example `13px`) will be replaced, the rest will be left as is, which means they'll get resolved at runtime. This solves your last point.
